---
apiVersion: v1
kind: Namespace
metadata:
  name: toolchain
  labels:
    app.kubernetes.io/name: toolchain
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: at41tools
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: tenant
    app.kubernetes.io/stage: prod
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: toolchain
  name: default-deny-inbound
  labels:
    app.kubernetes.io/name: default-deny-inbound
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: at41tools
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: tenant
    app.kubernetes.io/stage: prod
spec:
  podSelector: {}
  policyTypes:
    - Ingress
