---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: at41tools
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: admin-plane
    app.kubernetes.io/stage: devops
  name: alb-ingress-controller
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
      - pods/status
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: at41tools
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: admin-plane
    app.kubernetes.io/stage: devops
  name: alb-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alb-ingress-controller
subjects:
  - kind: ServiceAccount
    name: alb-ingress-controller
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: at41tools
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/tier: admin-plane
    app.kubernetes.io/stage: devops
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::389644296470:role/role-at41tools-alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
