rem eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/beget-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/berrothm-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/boehmj1-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/botaschj-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/buettnej-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/figans-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/haunert-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/kapernaa-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/ketterlm-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/koenigt-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/kuehnr2-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/laquac-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/maloyans-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/metzc-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/mixal-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/molnare-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/paetza-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/rachie-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/scheuc1-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/schmidts-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/scholzma-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/schroeds-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/schulzst-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/schwarad-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/szekelyv-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/szostaka-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/tjaens-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/todoreno-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/untriess-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/volkodas-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/worbsp-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/zimnikr-api --group system:masters --username admin
eksctl create iamidentitymapping --cluster eks-eu-west-1-cxp --arn arn:aws:iam::005913962162:user/zurawv-api --group system:masters --username admin
